export default {
  accessories: {
    earings: "../Assets/accessories/earings.png",
    flower: "../Assets/accessories/flower.png",
    glasses: "../Assets/accessories/glasses.png",
    headphone: "../Assets/accessories/headphone.png",
  },
  backgrounds: {
    blue50: "../Assets/backgrounds/blue50.png",
    blue60: "../Assets/backgrounds/blue60.png",
    blue70: "../Assets/backgrounds/blue70.png",
    darkblue30: "../Assets/backgrounds/darkblue30.png",
    darkblue50: "../Assets/backgrounds/darkblue50.png",
    darkblue70: "../Assets/backgrounds/darkblue70.png",
    green50: "../Assets/backgrounds/green50.png",
    green60: "../Assets/backgrounds/green60.png",
    green70: "../Assets/backgrounds/green70.png",
    grey40: "../Assets/backgrounds/grey40.png",
    grey70: "../Assets/backgrounds/grey70.png",
    grey80: "../Assets/backgrounds/grey80.png",
    red50: "../Assets/backgrounds/red50.png",
    red60: "../Assets/backgrounds/red60.png",
    red70: "../Assets/backgrounds/red70.png",
    yellow50: "../Assets/backgrounds/yellow50.png",
    yellow60: "../Assets/backgrounds/yellow60.png",
    yellow70: "../Assets/backgrounds/yellow70.png",
  },
  ears: {
    default: "../Assets/ears/default.png",
    tiltbackward: "../Assets/ears/tilt-backward.png",
    tiltforward: "../Assets/ears/tilt-forward.png",
  },
  eyes: {
    angry: "../Assets/eyes/angry.png",
    default: "../Assets/eyes/default.png",
    naughty: "../Assets/eyes/naughty.png",
    panda: "../Assets/eyes/panda.png",
    smart: "../Assets/eyes/smart.png",
    star: "../Assets/eyes/star.png",
  },
  hair: {
    bang: "../Assets/hair/bang.png",
    curls: "../Assets/hair/curls.png",
    default: "../Assets/hair/default.png",
    elegant: "../Assets/hair/elegant.png",
    fancy: "../Assets/hair/fancy.png",
    quiff: "../Assets/hair/quiff.png",
    short: "../Assets/hair/short.png",
  },
  leg: {
    bubbletea: "../Assets/leg/bubble-tea.png",
    cookie: "../Assets/leg/cookie.png",
    default: "../Assets/leg/default.png",
    gameconsole: "../Assets/leg/game-console.png",
    tiltbackward: "../Assets/leg/tilt-backward.png",
    tiltforward: "../Assets/leg/tilt-forward.png",
  },
  mouth: {
    astonished: "../Assets/mouth/astonished.png",
    default: "../Assets/mouth/default.png",
    eating: "../Assets/mouth/eating.png",
    laugh: "../Assets/mouth/laugh.png",
    tongue: "../Assets/mouth/tongue.png",
  },
  neck: {
    bendbackward: "../Assets/neck/bend-backward.png",
    bendforward: "../Assets/neck/bend-forward.png",
    default: "../Assets/neck/default.png",
    thick: "../Assets/neck/thick.png",
  },
  nose: { nose: "../Assets/nose/nose.png" },
};
